# fly.toml app configuration file generated for rollercoaster-dev-frontend on 2025-04-02T19:04:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rollercoaster-dev-frontend'
primary_region = 'fra'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

# Static site-specific configuration
[http_service.concurrency]
  type = "connections"
  hard_limit = 200
  soft_limit = 150
