version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: atbadges-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: atbadges
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: atbadges-pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@atbadges.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  badge-engine:
    build:
      context: ../badge-engine
      dockerfile: Dockerfile
    container_name: atbadges-badge-engine
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/badge_engine
      NODE_ENV: development
    volumes:
      - ../badge-engine:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: atbadges-backend
    restart: unless-stopped
    depends_on:
      - postgres
      - badge-engine
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/atbadges
      BADGE_ENGINE_URL: http://badge-engine:3001/api
      PORT: 3000
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data:
  pgadmin_data: