FROM oven/bun:1.2.2-alpine

WORKDIR /app

# Install dependencies
COPY package.json bun.lock ./
RUN bun install

# Copy all files
COPY . .

# Generate migrations
RUN bunx drizzle-kit generate:pg

# Expose the port the app will run on
EXPOSE 3000

# Start the application in development mode
CMD ["bun", "--watch", "index.ts"]